#!/usr/bin/env python3
"""
Generate the five preview pages.

The chrome (unofficial ribbon, utility bar, brand bar, the club's nav, the sub-nav across
these previews, footer) is identical on every page, so it lives here. Run `python3 build.py`
and commit the HTML it writes; GitHub Pages serves plain static files.
"""

import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Published Pool Relay views. Each is scoped to exactly what its page is about.
EMBED = {
    "home":    "uG9BcxGJkfV0NwQSC5PC2o",   # the whole club, a week at a time, Pools menu
    "lanes":   "FIPvohrJDuTwwf7MQbrcsm",   # the main pool, lane by lane, a day at a time
    "lessons": "XLkX6NFMUWScUH74uqyar0",   # Swim Lessons
    "team":    "wfvJeARSms5bthReYCVcVq",   # Swim Team and Masters
    "fitness": "Ll7hNgxmoFmsajp4On5kYO",   # Aqua Fitness and Rec Swim
}

NAV = [
    ("index.html",         "Meadowbrook"),
    ("lane-schedule.html", "Lane Schedule"),
    ("swim-lessons.html",  "Swim Lessons"),
    ("swim-team.html",     "Swim Team"),
    ("fitness.html",       "Fitness"),
]

SITE = "https://www.gocoppermine.com/meadowbrook"
PDF = "https://www.gocoppermine.com/elements/meadowbrook/meadowbrook-lane-schedule_2_19_2026.pdf"


def cal(key, title, caption="", short=False):
    """One live calendar plus its caption line."""
    token = EMBED[key]
    cls = "cal short" if short else "cal"
    tail = f" &nbsp;&mdash;&nbsp; {caption}" if caption else ""
    return f"""  <div class="{cls}">
    <iframe src="https://www.poolrelay.com/embed/{token}"
            title="{title}" loading="lazy"></iframe>
  </div>
  <p class="capt">Live from Pool Relay &middot;
    <a href="https://www.poolrelay.com/v/{token}" target="_blank" rel="noopener">open the full calendar &rarr;</a>{tail}
  </p>
"""


def shell(slug, title, description, body):
    subnav = "\n".join(
        '    <li{on}><a href="{href}">{label}</a></li>'.format(
            on=' class="on"' if href == slug else "", href=href, label=label)
        for href, label in NAV)
    main_on = {"swim-lessons.html": "Swim Lessons", "swim-team.html": "Swim Team", "fitness.html": "Fitness"}.get(slug, "About")
    def item(label, href):
        on = ' class="on"' if label == main_on else ""
        ext = '' if href.endswith(".html") else ' target="_blank" rel="noopener"'
        return f'    <li{on}><a href="{href}"{ext}>{label}</a></li>'
    main = "\n".join([
        item("About", "index.html"),
        item("Membership", SITE),
        item("Swim Lessons", "swim-lessons.html"),
        item("Fitness", "fitness.html"),
        item("Swim Team", "swim-team.html"),
        item("Summer", SITE),
        item("News &amp; Upcoming Events", SITE),
    ])
    return f"""<!DOCTYPE html>
<!--
  UNOFFICIAL PREVIEW. Not a Coppermine website.
  Generated by build.py — edit that, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;600;700&family=Poppins:wght@600;700;800&family=Roboto:wght@500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
</head>
<body>

<div class="ribbon">
  <b>Unofficial preview.</b> Not a Coppermine page. A replica of the
  <a href="{SITE}" target="_blank" rel="noopener">Coppermine Meadowbrook pages</a>
  with live <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool&nbsp;Relay</a> calendars.
</div>

<div class="util"><div class="wrap">
  <a href="https://www.gocoppermine.com/" target="_blank" rel="noopener">Locations</a>
  <a href="https://www.gocoppermine.com/" target="_blank" rel="noopener">Health Clubs</a>
  <a class="on" href="index.html">Aquatics</a>
  <a href="https://www.gocoppermine.com/" target="_blank" rel="noopener">Club Teams</a>
  <a href="https://www.gocoppermine.com/" target="_blank" rel="noopener">Camps</a>
</div></div>

<header class="brandbar">
  <div class="wrap inner">
    <a class="mark" href="index.html">COPPERMINE<span class="city">MEADOWBROOK</span></a>
    <div class="tel">410-433-8300 &middot; mbkinfo@gocoppermine.com</div>
  </div>
</header>

<nav class="main">
  <ul>
{main}
  </ul>
</nav>

<nav class="sub">
  <ul>
{subnav}
  </ul>
</nav>

{body}
<footer>
  <div class="wrap">
    <p><strong>Unofficial preview.</strong> Built to show what the Meadowbrook pages would look like
    with a live calendar on each one. Not affiliated with Coppermine.</p>
    <p>Schedule transcribed 23 September 2026 from the
    <a href="{PDF}" target="_blank" rel="noopener">Meadowbrook Lane Schedule</a> (the PDF dated
    February 19, 2026) and the Meadowbrook pages on gocoppermine.com. Calendars by
    <a href="https://www.poolrelay.com" target="_blank" rel="noopener">Pool Relay</a>.</p>
  </div>
</footer>

</body>
</html>
"""


QUESTIONS = """<section class="wrap">
  <h2>Questions for the Meadowbrook team</h2>
  <p>Everything here was transcribed from what Meadowbrook publishes. These are the places where the
  schedule goes quiet or where we had to make a call &mdash; each one is also written on the calendar
  entry itself.</p>

  <ul class="qa">
    <li>
      <div class="q"><span class="tag gap">Gap</span>Is the February schedule still the fall schedule?</div>
      <div class="a">The lane schedule is a PDF named for February 19, 2026, with no dates printed on it.
      The calendar runs it from the week after. If the swim team or lesson times changed for the fall,
      the new ones go in from the day they start, and the winter ones stay behind them.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Are the white cells open lap swim?</div>
      <div class="a">Most of the grid is empty. Members presumably swim laps there, but the PDF doesn't
      say so, and the calendar doesn't book lanes nobody named. Say the word and every open lane shows
      as lap swim, lane by lane.</div>
    </li>
    <li>
      <div class="q"><span class="tag clash">Conflict</span>When does recreational swim run?</div>
      <div class="a">The Meadowbrook page says &ldquo;Recreational swim begins at 10AM&rdquo;. The lane
      schedule shows Rec Swim only on Saturday and Sunday, 2&ndash;6pm, in the Therapy Pool.</div>
    </li>
    <li>
      <div class="q"><span class="tag ours">Ours</span>Aqua Fitness on lanes 1&ndash;2</div>
      <div class="a">Monday, Wednesday and Friday, 9&ndash;11am, Aqua Fitness fills lanes 1&ndash;2 at both
      the deep and the shallow end. We entered that as one class using both ends.</div>
    </li>
    <li>
      <div class="q"><span class="tag gap">Gap</span>Masters in 50 m lane 3</div>
      <div class="a">On Tuesday, Thursday and Saturday, Masters also takes 50 m lane 3. Is that a
      long-course group, and does it have its own coach or sign-up?</div>
    </li>
  </ul>
</section>

"""


HOME = f"""<section class="wrap hero">
  <div class="crumb">Aquatics &raquo; Meadowbrook</div>
  <h1>Welcome to Coppermine Meadowbrook</h1>
  <p class="kicker">Mt. Washington, Maryland &middot; indoor/outdoor lap lanes, 25-yard and 50-meter</p>
  <p class="lead">A historic aquatic center just off Falls Road in Mt. Washington, North Baltimore:
  lap lanes, swim lessons, a swim team, Masters, aqua fitness and a therapy pool. Here is the whole
  week, every pool. Use the <strong>Pools</strong> menu to show one.</p>

{cal("home", "Coppermine Meadowbrook — this week", "Every program in every pool, with the lanes it uses.")}
  <p><a class="btn-copper" href="lane-schedule.html">See the lane-by-lane schedule &rarr;</a></p>
</section>

<section class="wrap">
  <h2>Hours &amp; location</h2>
  <div class="facts">
    <div><b>Monday &ndash; Saturday</b>5:30am &ndash; 8:00pm</div>
    <div><b>Sunday</b>10:00am &ndash; 8:00pm</div>
    <div><b>Address</b>5700 Cottonworth Avenue, Baltimore, MD 21209</div>
    <div><b>Contact</b>410-433-8300 &middot; mbkinfo@gocoppermine.com</div>
  </div>
</section>

{QUESTIONS}"""


LANES = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Meadowbrook</a> &raquo; Lane Schedule</div>
  <h1>Lane Schedule</h1>
  <p class="kicker">Deep 25 m &middot; shallow 25 yd &middot; 50 m &middot; one day at a time</p>
  <p class="lead">Every lane of the main pool, side by side: the deep-end 25-meter lanes D1, D2, D5 and D6,
  the shallow-end 25-yard lanes S1, S2, S5 and S6, and the 50-meter lanes L3 and L4. Use the arrows to
  move a day.</p>

{cal("lanes", "Coppermine Meadowbrook — lane by lane", "Each block sits in the lanes it uses, for as long as it runs.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Four pages become one</h2>
    <p class="q">&ldquo;Is there a lane open at 7:00 on Tuesday morning?&rdquo;</p>
    <p>Today that answer is spread over a four-page PDF: Deep 25M lanes, Shallow 25Y lanes, 50M lanes and
    the Therapy Pool, each with seven days of four narrow columns and thirty half-hour rows.</p>
    <p class="answer">Here it is one day, every lane, read across: <b>at 7:00 on Tuesday the whole main
    pool is clear</b> &mdash; Masters has just finished, and the swim team isn't in until 3:30.</p>
  </div>
</div>

{QUESTIONS}"""


LESSONS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Meadowbrook</a> &raquo; Swim Lessons</div>
  <h1>Swim Lessons</h1>
  <p class="kicker">Group and private lessons &middot; therapy pool and shallow lanes</p>
  <p class="lead">Lessons run most of the day in the Therapy Pool, weekday afternoons in shallow lane S1
  (and S2 from 5:30), weekend mornings, and in deep lanes D1&ndash;D2 on Monday, Wednesday and Friday
  evenings.</p>

{cal("lessons", "Coppermine Meadowbrook Swim Lessons — the lesson week", "Each block shows the pool and the lanes the lesson uses.")}
</section>

<div class="trail">
  <div class="wrap">
    <h2>Which water is my child in?</h2>
    <p>On the lane schedule, lessons are a yellow cell in whichever of four grids they fall on. A parent
    looking for a 5:30 lesson has to check the shallow lanes and the Therapy Pool page to find it.</p>
    <p class="answer">Here every lesson block says where it is: <b>Therapy Pool, shallow lane S1, or
    deep lanes D1&ndash;D2</b> &mdash; so a parent knows where to stand before they arrive.</p>
  </div>
</div>

"""


TEAM = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Meadowbrook</a> &raquo; Swim Team</div>
  <h1>Swim Team</h1>
  <p class="kicker">Deep 25 m lanes &middot; six days a week &middot; Masters mornings</p>
  <p class="lead">The swim team trains in the deep-end 25-meter lanes: weekday afternoons from 3:30
  (until 7:00 on Monday, Wednesday and Friday, 8:00 on Tuesday and Thursday), Saturday 7:30&ndash;11:00
  and Sunday 11:00&ndash;1:00. Masters swims 6:00&ndash;7:00am, Monday to Saturday.</p>

{cal("team", "Coppermine Meadowbrook Swim Team — the practice week", "Swim Team and Masters, with the lanes each practice takes.")}
</section>

{QUESTIONS}"""


FITNESS = f"""<section class="wrap hero">
  <div class="crumb"><a href="index.html">Meadowbrook</a> &raquo; Fitness</div>
  <h1>Aqua Fitness &amp; Rec Swim</h1>
  <p class="kicker">Lanes 1&ndash;2 and the Therapy Pool</p>
  <p class="lead">Aqua Fitness runs Monday, Wednesday and Friday, 9:00&ndash;11:00 in lanes 1&ndash;2 at
  both ends of the main pool and 11:00&ndash;noon in the Therapy Pool. Rec Swim is in the Therapy Pool on
  Saturday and Sunday afternoons.</p>

{cal("fitness", "Coppermine Meadowbrook Aqua Fitness — the class week", "Every class and rec swim, with its pool and lanes.")}
</section>

"""

PAGES = [
    ("index.html", "Coppermine Meadowbrook (Pool Relay preview)",
     "Unofficial preview of the Coppermine Meadowbrook page with a live Pool Relay calendar of the whole club.", HOME),
    ("lane-schedule.html", "Lane Schedule &mdash; Coppermine Meadowbrook (Pool Relay preview)",
     "Unofficial preview: the Meadowbrook lane schedule, every lane side by side, one day at a time.", LANES),
    ("swim-lessons.html", "Swim Lessons &mdash; Coppermine Meadowbrook (Pool Relay preview)",
     "Unofficial preview: Meadowbrook swim lessons, with the pool and lanes of every lesson.", LESSONS),
    ("swim-team.html", "Swim Team &mdash; Coppermine Meadowbrook (Pool Relay preview)",
     "Unofficial preview: the Meadowbrook swim team and Masters practice week.", TEAM),
    ("fitness.html", "Aqua Fitness &mdash; Coppermine Meadowbrook (Pool Relay preview)",
     "Unofficial preview: Meadowbrook aqua fitness and rec swim.", FITNESS),
]

if __name__ == "__main__":
    for slug, title, description, body in PAGES:
        html = shell(slug, title, description, body)
        with io.open(os.path.join(HERE, slug), "w", encoding="utf-8") as f:
            f.write(html)
        print(f"wrote {slug} ({len(html.encode()):,} bytes)")
